{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tuxmart-logto.fullname" . }}
  labels:
    {{- include "tuxmart-logto.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "tuxmart-logto.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- range .Values.networkPolicy.ingress }}
    - from:
        {{- toYaml .from | nindent 8 }}
      ports:
        {{- toYaml .ports | nindent 8 }}
    {{- end }}
    {{- if .Values.sidecar.enabled }}
    {{- range .Values.sidecar.ports }}
    - ports:
        - port: {{ .listenPort }}
          protocol: TCP
    {{- end }}
    {{- end }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 5432
          protocol: TCP
        - port: 443
          protocol: TCP
        - port: 80
          protocol: TCP
{{- end }}
