apiVersion: v1
kind: Service
metadata:
  name: {{ include "tuxmart-logto.fullname" . }}
  labels:
    {{- include "tuxmart-logto.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    {{- range .Values.service.ports }}
    {{- $servicePortName := .name }}
    {{- $targetPort := .targetPort }}
    {{- if $.Values.sidecar.enabled }}
    {{- range $.Values.sidecar.ports }}
    {{- if eq .name $servicePortName }}
    {{- $targetPort = .listenPort }}
    {{- end }}
    {{- end }}
    {{- end }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ $targetPort }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "tuxmart-logto.selectorLabels" . | nindent 4 }}
